# Generated by Django 3.2.15 on 2022-10-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, null=True, verbose_name='Описание')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1500, null=True, verbose_name='Описание')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создание')),
                ('update_date', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('code', models.IntegerField(null=True, verbose_name='Артикул')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market_place.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
