# Generated by Django 3.2.15 on 2022-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0002_goods_remaining_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Артикул'),
        ),
    ]
