# Generated by Django 3.2.15 on 2022-10-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0003_alter_goods_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Артикул'),
        ),
    ]
