# Generated by Django 3.2.15 on 2022-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_purchasedgoods'),
        ('app_market_place', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sold',
            field=models.ManyToManyField(blank=True, to='app_users.PurchasedGoods', verbose_name='Куплена'),
        ),
    ]
