# Generated by Django 3.2.15 on 2022-10-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0014_auto_20221028_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='sold',
            new_name='purchases',
        ),
    ]
