# Generated by Django 3.2.15 on 2022-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0001_initial'),
        ('app_users', '0002_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(null=True, to='app_market_place.Goods', verbose_name='Корзина'),
        ),
    ]
