# Generated by Django 3.2.15 on 2022-10-23 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market_place', '0004_alter_goods_code'),
        ('app_users', '0005_auto_20221023_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedGoods',
            new_name='PurchasedGood',
        ),
    ]
