# Generated by Django 3.2.15 on 2022-10-23 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0004_alter_goods_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0006_rename_purchasedgoods_purchasedgood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedGood',
            new_name='PurchasedGoods',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
