# Generated by Django 3.2.15 on 2022-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20221023_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_sum',
            field=models.IntegerField(null=True, verbose_name='Сумма к оплате'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_good_price_sum',
            field=models.IntegerField(null=True, verbose_name='Цена товара'),
        ),
    ]
