# Generated by Django 3.2.15 on 2022-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_profile_payment_for_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_for_cart',
            field=models.PositiveIntegerField(default=0, verbose_name='На оплату'),
        ),
    ]
