# Generated by Django 3.2.15 on 2022-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_alter_profile_payment_for_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedgoods',
            name='good_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
