# Generated by Django 3.2.15 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_purchasedgoods_good_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('b', 'Basic'), ('v', 'VIP')], default='b', max_length=1, verbose_name='Статус'),
        ),
    ]
