# Generated by Django 3.2.15 on 2022-10-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='good',
        ),
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='PurchasedGoods',
        ),
    ]
