# Generated by Django 3.2.15 on 2022-10-27 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_place', '0007_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0014_auto_20221026_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('purchase_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата покупки')),
                ('purchase_sum', models.IntegerField(null=True, verbose_name='Сумма покупки')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market_place.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приобретенный товар',
                'verbose_name_plural': 'Приобретенные товары',
            },
        ),
    ]
