# Generated by Django 3.2.15 on 2022-10-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_purchasedgoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedgoods',
            old_name='good',
            new_name='good_obj',
        ),
        migrations.AddField(
            model_name='purchasedgoods',
            name='good_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название товара'),
        ),
    ]
