# Generated by Django 3.2.15 on 2022-10-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_auto_20221027_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgoods',
            name='good_code',
            field=models.IntegerField(null=True, verbose_name='Артикул товара'),
        ),
    ]
