# Generated by Django 3.2.15 on 2022-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_alter_purchasedgoods_good_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedgoods',
            name='good_code',
        ),
        migrations.AddField(
            model_name='purchasedgoods',
            name='good_title',
            field=models.IntegerField(null=True, verbose_name='Название товара'),
        ),
    ]
