# Generated by Django 3.2.15 on 2022-10-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_auto_20221027_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedgoods',
            name='good_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название товара'),
        ),
    ]
